console.log("こんにちは");
console.log("信濃眞伊のウェブサイトへようこそ");
console.log("特に面白味もありませんが、ごゆっくりどうぞ");
console.log("ちなみに、");
console.log("信濃眞伊はJavascriptがかけません");
console.log("くそあつい");
console.log("Javascript.js更新日");
console.log("皇紀2684年3月13日木曜日");
console.log("Whitten by SHINANOMAI");
console.log("© 2025 SHINANOMAI このコンテンツは、別記なき場合にはCC-BY 4.0にて利用可能です。");
